using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FirstProgram1
{
    public class flipcoin
    {
        public static void flipthecoin()
        {
            Console.WriteLine("please enter the value for the number of flips");
            int head = 0;
            int tail = 0;
             double headpercentage = 0.0;
            double tailpercentage = 0.0;

            int flip = Convert.ToInt32(Console.ReadLine());
            if (flip > 0)
            {
                for(int i = 0; i < flip; i++)
                {
                    Random random = new Random();
                    int num = random.Next(2);
                    Console.WriteLine("Random number generated by system" + num);
                    if(num == 0)
                    {
                        Console.WriteLine("it a tail");
                        tail = tail + 1;
                        //tail++;

                    }
                    else
                    {
                        Console.WriteLine("it is head");
                        head = head + 1;
                    }
                }
                Console.WriteLine("the head count is" + head);
                Console.WriteLine("the tail count is" + tail);

                headpercentage = head * 100 / flip;
                tailpercentage = tail * 100 / flip;
                Console.WriteLine("head percentage" + headpercentage);
                Console.WriteLine("tail percentage" + tailpercentage);

            }
        }
    }
}
